name: make report

on:
  schedule:
    # 毎日 00:00 UTC (09:00 JST)
    - cron: "0 0 * * *"
    # 毎月1日 00:00 UTC (09:00 JST)
    # - cron: "0 0 1 * *"
    # 毎日曜 00:00 UTC (09:00 JST)
    #- cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  make_report_cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Git 設定
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: タグ作成
        id: tag
        run: |
          TAG="v$(date +'%Y.%m.%d')"

          # すでにタグが存在する場合は時分秒を付与
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            TAG="v$(date +'%Y.%m.%d-%H%M%S')"
          fi

          #TAG="v$(date +'%Y.%m.%d-%H%M%S')"

          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

          git tag "$TAG"
          git push origin "$TAG"

      - name: Python をセットアップ
        uses: actions/setup-python@v6

      - name: Python ライブラリをセットアップ
        run: |
          sudo apt update

      - name: コマンドをセットアップ
        run: |
          sudo apt update
          sudo apt install -y mailutils

      - name: make report
        run: |
          python admin.py

      # 生成したファイルをコミット＆プッシュ
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated File Generation"
          file_pattern: "report.html" # 対象ファイル（すべて指定する場合は '.'）

      - name: Upload binaries to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.tag }}
          artifacts: report.html
          bodyFile: body.md

      - name: Prepare Pages
        run: |
          mkdir public
          cp report.html public/index.html

      - uses: actions/upload-pages-artifact@v5
        with:
          path: public

      - name: Send mail (mail command)
        run: |
          echo "${{ secrets.EMAIL }}"
          echo "Github Actions done." | mail -s "Github Actions done." "${{ secrets.EMAIL }}"

  deploy:
    needs: make_report_cron
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v7
